{"error": "ERREUR: unhashable type: 'dict'\nTraceback (most recent call last):\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\routes.py\", line 84, in process_clash_detection\n    clashes = detector.detect_clashes()\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\clash_detection.py\", line 202, in detect_clashes\n    found_clashes = self._detect_between_models_optimized(model_a, model_b)\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\clash_detection.py\", line 245, in _detect_between_models_optimized\n    candidates = spatial_grid.get_candidates(elem_a, self.tolerance)\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\clash_detection.py\", line 53, in get_candidates\n    candidates.update(self.grid[(x,y,z)])\nTypeError: unhashable type: 'dict'\n", "status": "failed"}