{"error": "ERREUR: cannot schedule new futures after interpreter shutdown\nTraceback (most recent call last):\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\routes.py\", line 84, in process_clash_detection\n    print(f\"Clashs d\u00e9tect\u00e9s: {len(clashes)}\")\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\clash_detection.py\", line 177, in detect_clashes\n    found_clashes = self._detect_between_models(model_a, model_b)\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\clash_detection.py\", line 281, in _detect_between_models\n    futures.append(executor.submit(\n  File \"C:\\Python310\\lib\\concurrent\\futures\\thread.py\", line 169, in submit\n    raise RuntimeError('cannot schedule new futures after '\nRuntimeError: cannot schedule new futures after interpreter shutdown\n", "status": "failed"}