{"error": "ERREUR: unhashable type: 'dict'\nTraceback (most recent call last):\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\routes.py\", line 84, in process_clash_detection\n    clashes = detector.detect_clashes()\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\clash_detection.py\", line 279, in detect_clashes\n    found_clashes = self._detect_between_models_optimized(model_a, model_b)\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\clash_detection.py\", line 314, in _detect_between_models_optimized\n    candidates.update(spatial_grid.grid.get((x,y,z), []))\nTypeError: unhashable type: 'dict'\n", "status": "failed"}